# Generated by Django 2.1.7 on 2019-02-21 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('korean_name', models.CharField(blank=True, default='', max_length=20)),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('gender', models.CharField(max_length=6)),
                ('language', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('interest', models.CharField(max_length=50)),
                ('church', models.CharField(max_length=100)),
                ('church_position', models.CharField(blank=True, default='', max_length=50)),
                ('training', models.TextField(blank=True, default='')),
                ('leader', models.BooleanField(blank=True, default='')),
                ('staff', models.BooleanField(blank=True, default='')),
                ('school', models.CharField(blank=True, default='', max_length=50)),
                ('grade', models.CharField(blank=True, default='', max_length=20)),
                ('major', models.CharField(blank=True, default='', max_length=50)),
                ('company', models.CharField(blank=True, default='', max_length=50)),
                ('company_position', models.CharField(blank=True, default='', max_length=50)),
                ('shirt_size', models.CharField(blank=True, default='', max_length=10)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=50)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('zip_code', models.IntegerField(blank=True, default='')),
                ('attendee_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('event_description', models.TextField(blank=True)),
                ('event_start', models.DateField()),
                ('event_end', models.DateField()),
                ('event_start_time', models.TimeField()),
                ('event_end_time', models.TimeField()),
                ('event_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('column_name', models.CharField(max_length=100)),
                ('original_value', models.TextField()),
                ('new_value', models.TextField()),
                ('log_created', models.DateTimeField(auto_now_add=True)),
                ('attendee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.Attendee')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(blank=True, max_length=10)),
                ('value', models.CharField(max_length=200)),
                ('reference_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField()),
                ('staff', models.BooleanField()),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=20)),
                ('shirt_size', models.CharField(max_length=10)),
                ('health', models.TextField(blank=True)),
                ('prayer_topic', models.CharField(blank=True, max_length=200)),
                ('registration_created', models.DateTimeField(auto_now_add=True)),
                ('attendee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.Attendee')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_name', models.CharField(max_length=200)),
                ('ticket_description', models.TextField()),
                ('ticket_price', models.IntegerField()),
                ('ticket_start', models.DateField()),
                ('ticket_end', models.DateField()),
                ('ticket_created', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_id', models.IntegerField()),
                ('payment_type', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('gateway', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('expires', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attendee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.Attendee')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.Event')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.Ticket')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hello.Ticket'),
        ),
    ]
